name: HappyChaosMonsters
favicon: null
layout_spectrum: 0.4330388172529638
typography_spectrum: 0.9073977649677545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9387780928518623
  lightness: 0.3328853810671717
  saturation: 0.8041001411620528
  rhythmicContrast: 0.2733662815298885
purpose: []
