name: HappyChaosMonsters
favicon: null
layout_spectrum: 0.4330388172529638
typography_spectrum: 0.08804
title: HAPPY CHAOS MONSTERS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef388'
    - '#010000'
    - '#1aa8a7'
    - '#83c04b'
    - '#842264'
  brandStrength: 0.9387780928518623
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
